# Generated by Django 4.2.6 on 2023-10-18 09:15

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_created_at_document_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
